### ISSUE TITLE
[question] VS Code IntelliSense autocomplete?

### ISSUE THREAD

**Issue by Fghurayri** [flayyer/next-rosetta#14]
Hey @lopezjurip,

Thank you so much for the great library; providing type safety for the translation keys is awesome! 🙌

I just wanted to know if you and folks are enjoying the VS Code IntelliSense autocomplete? In my case, it doesn't work, although I believe it should, since I see the red squiggly lines when I type the translation key incorrectly.

Here is a minimal version for my setup:

index.ts
```ts
export interface Locale {
  common: {
    welcome: string;
  }
}
```

en.ts
```ts
import type { Locale } from ".";
export const table: Locale = {
  common: {
    welcome: "Welcome",
  },
};
```
index.tsx
```ts
import { GetStaticProps } from "next";
import { I18nProps, useI18n } from "next-rosetta";
import { Locale } from "../lib/locales";

export default function Home() {
  const { t } = useI18n<Locale>();
  return (
    <div>{t("c")}</div>
  );
}

export const getStaticProps: GetStaticProps<I18nProps<Locale>> = async (
  context
) => {
  const locale = context.locale || context.defaultLocale;
  const { table = {} } = await import(`../lib/locales/${locale}`);
  return { props: { table } };
};

```

Here is the result when I hit ctrl+space to see the IntelliSense autocomplete suggestions:

<img width="684" alt="Screen Shot 2021-06-10 at 23 36 10" src="https://user-images.githubusercontent.com/27068874/121627136-cd8ba500-ca44-11eb-9153-53a22e4b9735.png">

**Comment by lopezjurip** [comment]
Hi @Fghurayri! This is a limitation from VSCode and how TypeScript handles Template literal and Recursive types. It only will autocomplete once the string path is valid:

```ts
const foo = t("common.welcome"); // will have type string
const baz = t("c");              // will have type unknown
const bar = t("common.w3lcom");  // will have type unknown
```

There are some ways to achieve partial autocompletion but it requires to generate types via a script, here is an example of a project but for Tailwindcss: https://github.com/muhammadsammy/tailwindcss-classnames

**Comment by Fghurayri** [comment]
Thank you for your clarification and the shared link. 👍
