### ISSUE TITLE
Is this repository MIT licensed?

### ISSUE THREAD

**Issue by wiselucky** [flayyer/next-rosetta#19]
There is no LICENSE file in this repository.

but, [NPM in this repository](https://www.npmjs.com/package/next-rosetta) is under the MIT license.

Is this repository MIT licensed?

**Comment by lopezjurip** [comment]
Yes MIT license 👍  I will add that, thanks!

**Comment by lopezjurip** [comment]
https://github.com/flayyer/next-rosetta/commit/f9bffb81b80e3e320820abdad880041e6a150cfc
