### ISSUE TITLE
API is incompatible between Minor versions

### ISSUE THREAD

**Issue by jupardo** [flayyer/next-rosetta#5]
I've found that 1.2.3 t method is incompatible with previous signatures, as version 1.1 supports using an array as key but 1.2 doesn't support that. Is there any plan to implement support for using array as key in future versions? Or shall we stop using t([]) signature?

**Comment by lopezjurip** [comment]
Hi @jupardo, sorry we forgot about the `[]` signature. I just updated the typings to not display it as an error but the returned type will be `unknown`.

```
yarn add next-rosetta@1.2.2
```

We are still trying to make dot and array path notation work with type inference. 

If you have type issues when rendering with react cast them `as any`

**Comment by jupardo** [comment]
Thank you!
